source:      .
destination: ./_site
layouts_dir: ./_layouts

future:      false

permalink:     pretty
paginate_path: 'page:num'
paginate: 10

excerpt_separator: "<!-- more -->"

inc:
  # Blog Information
  title:        "Source @ Coveo"
  subtitle:     "A technical blog by the fine people at Coveo"
  cover_image:  blog-cover.jpg
  logo:         logo2.png

  # Company information
  company:      Coveo
  url:          https://www.coveo.com/
  twitter:      coveo

  # Comments
  disqus:
    shortname:  coveordblog #false to disable

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   false
    gplus:      false
    hn:         false
    foursquare: false

 # Analytics
  analytics:
    google: true
    coveo: true

plugins:
    - jekyll-paginate
    - jekyll-sitemap
exclude: ['Gemfile', 'Gemfile.lock']
