inc:
  # Blog Information
  title:        "Source @ Coveo"
  subtitle:     "A technical blog by the fine people at Coveo"
  cover_image:  blog-cover.jpg
  logo:         logo.png

  # Company information
  company:      Coveo
  url:          http://www.coveo.com/
  twitter:      coveodev

  # Comments
  disqus:
    shortname:  coveordblog #false to disable

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   false
    gplus:      false
    hn:         false
    foursquare: false


 # Analytics
  analytics:
    google: true
    coveo: true

  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'
  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

source:      .
destination: ./_site
layouts_dir: ./_layouts

base_url: ""
url: http://source.coveo.com

# Show future posts
future:      false
highlighter: pygments

permalink:     pretty
paginate_path: 'page:num'
paginate: 10

excerpt_separator: "<!-- more -->"

host:        127.0.0.1
port:        4000

gems: [jekyll-paginate]